# E-Commerce Sales Queries :-

SELECT Date , SUM(AMOUNT) FROM ECOMMERCE_SALES GROUP BY Date ORDER BY SUM(AMOUNT) DESC;
SELECT Channel, SUM(Amount) FROM ECOMMERCE_SALES GROUP BY Channel ORDER BY SUM(Amount) DESC;
SELECT Channel , COUNT(Category) FROM ECOMMERCE_SALES GROUP BY Channel ORDER BY COUNT(Category) DESC;
SELECT Age, SUM(Amount) FROM  ECOMMERCE_SALES GROUP BY Age ORDER BY SUM(Amount) DESC;

ALTER TABLE ECOMMERCE_SALES RENAME COLUMN `Cust ID` TO Cust_ID;

SELECT Size, COUNT(Cust_ID), SUM(Amount) FROM ECOMMERCE_SALES GROUP BY Size ORDER BY SUM(Amount) DESC;

ALTER TABLE ECOMMERCE_SALES RENAME COLUMN `ship-state` TO City;
SELECT City, SUM(Amount) AS TOP_5_CITY_SALES FROM ECOMMERCE_SALES GROUP BY City ORDER BY  SUM(Amount) DESC LIMIT 5;

SELECT B2B, COUNT(Cust_ID), SUM(Amount) FROM ECOMMERCE_SALES GROUP BY B2B;